version: "3"

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: microservice-auth
    environment:
      - APP_CONFIG_PATH=./config.py
    env_file: app.env
    ports:
      - "8000:8000"
